import type { AppState } from './types'

export const initialState: AppState = {
  runtimeMode: 'browser_preview_mock',
  currentProfileId: 'example-provider-a',
  configPath: String.raw`C:\Users\<user>\.codex\config.toml`,
  authPath: String.raw`C:\Users\<user>\.codex\auth.json`,
  autoStart: false,
  backupPolicy: {
    automaticLimit: 3,
    manualLimit: 3,
  },
  configurationProtection: {
    baselineReady: true,
    baselineDetail: '首次启动基线备份已创建，包含本工具可能写入的 Codex 设置和本机登录信息。',
    restoreDetail: '只恢复服务商设置；其他内容保持不变。',
    items: [
      { id: 'mcp-servers', label: 'MCP 服务', count: 3, state: 'protected', detail: '已设置 3 项，切换时会保留。' },
      { id: 'plugins', label: '插件设置', count: 2, state: 'protected', detail: '已设置 2 项，切换时会保留。' },
      { id: 'projects', label: '项目设置', count: 4, state: 'protected', detail: '已设置 4 项，切换时会保留。' },
      { id: 'hooks', label: '自动化规则', count: 5, state: 'protected', detail: '已设置 5 项，切换时会保留。' },
      { id: 'features', label: '功能偏好', count: 3, state: 'protected', detail: '已设置 3 项，切换时会保留。' },
      { id: 'history', label: '聊天与历史记录', state: 'outside_write_scope', detail: '不属于本工具读写范围，不会读取或改写。' },
    ],
  },
  connectionEnvironment: {
    status: 'ready',
    selectedLayerId: 'user-config',
    onboardingCompleted: true,
    detail: '已准备当前 Codex 用户配置。切换时只会改服务商字段，其余设置会保留。',
    layers: [
      { id: 'user-config', label: '当前 Codex 用户配置', detail: '本机配置层，保存后立即生效。', selected: true },
      { id: 'work-profile', label: '工作 profile 配置', detail: '可选择的配置层，不会自动合并。', selected: false },
    ],
  },
  profiles: [
    {
      id: 'example-provider-c',
      name: '服务商 C',
      baseUrl: 'https://provider-c.example/v1',
      model: 'reasoning-preview',
      reasoningEffort: 'high',
      note: '最近一次额度检查未通过。',
      verified: false,
      verificationStatus: 'billing_unavailable',
      isDefault: true,
      active: false,
      hasApiKey: true,
      lastVerifiedAt: '2026-07-29 10:42',
      lastVerificationDetail: '服务商返回额度不足，未写入 Codex 配置。',
      lastVerificationStage: 'billing',
      lastVerificationHttpStatus: 429,
      lastVerificationProviderCode: 'insufficient_quota',
    },
    {
      id: 'example-provider-b',
      name: '服务商 B',
      baseUrl: 'https://provider-b.example/v1',
      model: '',
      reasoningEffort: 'high',
      note: '等待确认响应格式。',
      verified: false,
      verificationStatus: 'response_shape_unconfirmed',
      isDefault: false,
      active: false,
      hasApiKey: true,
      lastVerifiedAt: '2026-07-29 10:38',
      lastVerificationDetail: '服务端已返回 JSON，但无法确认其可供 Codex 使用。',
      lastVerificationStage: 'response_shape',
      lastVerificationHttpStatus: 200,
    },
    {
      id: 'example-provider-d',
      name: '服务商 D',
      baseUrl: 'https://provider-d.example/v1',
      model: 'gpt-5.6-terra',
      reasoningEffort: 'high',
      note: '连接检查已通过。',
      verified: true,
      verificationStatus: 'verified',
      isDefault: false,
      active: false,
      hasApiKey: true,
      lastVerifiedAt: '2026-07-29 10:34',
      lastVerificationDetail: '短时 Responses 请求返回可识别的模型输出。',
      lastVerificationStage: 'inference',
      lastVerificationHttpStatus: 200,
      verificationResponseShape: 'standard_responses',
    },
    {
      id: 'example-provider-a',
      name: '服务商 A',
      baseUrl: 'https://provider-a.example/v1',
      model: 'gpt-5.6-terra',
      reasoningEffort: 'high',
      note: '当前配置已验证。',
      verified: true,
      verificationStatus: 'verified',
      isDefault: false,
      active: true,
      hasApiKey: true,
      lastSwitchedAt: '2026-07-01 22:10',
      lastVerifiedAt: '2026-07-29 10:36',
      lastVerificationDetail: '短时 Responses 请求返回可识别的模型输出。',
      lastVerificationStage: 'inference',
      lastVerificationHttpStatus: 200,
      verificationResponseShape: 'standard_responses',
    },
  ],
  modelCatalogs: [
    {
      providerId: 'example-provider-a',
      baseUrl: 'https://provider-a.example/v1',
      fetchedAt: '2026-07-14 18:00:00',
      lastSuccessfulAt: '2026-08-18 17:42:00',
      status: 'ok',
      statusDetail: '已刷新 4 个可用模型。',
      models: [
        { id: 'gpt-5.6-sol', aliases: ['5.6 sol'], source: 'mock', tags: ['codex', '推理'], verifiedForResponses: 'verified' },
        { id: 'gpt-5.6-terra', aliases: ['5.6 terra'], source: 'mock', tags: ['codex', '推理'], verifiedForResponses: 'verified' },
        { id: 'gpt-5.6-luna', aliases: ['5.6 luna'], source: 'mock', tags: ['codex', '快速'], verifiedForResponses: 'unknown' },
        { id: 'gpt-5.5', aliases: ['5.5'], source: 'mock', tags: ['codex'], verifiedForResponses: 'verified' },
      ],
    },
    {
      providerId: 'example-provider-d',
      baseUrl: 'https://provider-d.example/v1',
      fetchedAt: '2026-08-18 17:40:00',
      lastSuccessfulAt: '2026-08-18 17:40:00',
      status: 'ok',
      statusDetail: '已刷新 4 个模型。',
      models: [
        { id: 'gpt-5.6-sol', aliases: ['5.6 sol'], source: 'mock', tags: ['codex', '推理'], verifiedForResponses: 'verified' },
        { id: 'gpt-5.6-terra', aliases: ['5.6 terra'], source: 'mock', tags: ['codex', '推理'], verifiedForResponses: 'verified' },
        { id: 'gpt-5.6-luna', aliases: ['5.6 luna'], source: 'mock', tags: ['codex', '快速'], verifiedForResponses: 'unknown' },
        { id: 'gpt-5.5', aliases: ['5.5'], source: 'mock', tags: ['codex'], verifiedForResponses: 'verified' },
      ],
    },
  ],
  checks: [
    {
      id: 'toml',
      label: 'TOML 语法',
      ok: true,
      detail: '配置文件可以正常解析。',
      severity: 'required',
    },
    {
      id: 'root-model',
      label: 'Codex 模型',
      ok: true,
      detail: '根配置中已设置 model。',
      severity: 'required',
    },
    {
      id: 'model-provider',
      label: 'model_provider 已锁定',
      ok: true,
      detail: '已保留预期的 custom 服务商分组。',
      severity: 'required',
    },
    {
      id: 'custom-provider',
      label: 'custom 服务商配置段',
      ok: true,
      detail: '[model_providers.custom] 存在。',
      severity: 'required',
    },
    {
      id: 'wire-api',
      label: 'Responses 线路协议',
      ok: true,
      detail: 'wire_api 保持 responses，兼容 Codex 原生请求。',
      severity: 'required',
    },
    {
      id: 'custom-base-url',
      label: '当前接口地址',
      ok: true,
      detail: 'custom 服务商已配置 base_url。',
      severity: 'required',
    },
    {
      id: 'custom-authentication-mode',
      label: '当前认证方式',
      ok: true,
      detail: '当前服务商未声明认证方式；不会要求或写入 api_key。',
      severity: 'required',
    },
  ],
  activity: [
    {
      id: 'act-1',
      time: '22:26',
      title: '配置安全检查完成',
      detail: 'Codex 当前配置和当前服务商必填项已完成本地检查。',
      tone: 'success',
    },
    {
      id: 'act-2',
      time: '22:13',
      title: '已切换到服务商 A',
      detail: '切换前已生成 config.toml 和 auth.json 回滚点。',
      tone: 'success',
    },
    {
      id: 'act-3',
      time: '22:11',
      title: '备份已生成',
      detail: 'before-20260701-221054 可用于高级恢复。',
      tone: 'info',
    },
  ],
  costCalibrations: [
    {
      id: 'cost-demo-d',
      providerId: 'example-provider-d',
      providerName: '服务商 D',
      fundingMode: 'prepaid',
      paidCny: '10',
      consumableCredit: '1000',
      debitCredit: '0.000398',
      creditUnitLabel: '平台额度',
      model: 'gpt-5.6-terra',
      probeVersion: 'cost-calibration-v2',
      costSource: 'response_usage',
      probeId: 'probe-demo-d',
      sampleKind: 'cold',
      resultCny: '0.00000398',
      state: 'completed',
      createdAt: '2026-08-07 20:16',
      updatedAt: '2026-08-07 20:16',
    },
    {
      id: 'cost-demo-a',
      providerId: 'example-provider-a',
      providerName: '服务商 A',
      fundingMode: 'prepaid',
      paidCny: '10',
      consumableCredit: '1000',
      debitCredit: '0.000524',
      creditUnitLabel: '平台额度',
      model: 'gpt-5.6-terra',
      probeVersion: 'cost-calibration-v2',
      costSource: 'billing_log_manual',
      probeId: 'probe-demo-a',
      sampleKind: 'cold',
      resultCny: '0.00000524',
      state: 'completed',
      createdAt: '2026-08-07 20:12',
      updatedAt: '2026-08-07 20:12',
    },
    {
      id: 'cost-demo-a-repeat',
      providerId: 'example-provider-a',
      providerName: '服务商 A',
      fundingMode: 'prepaid',
      paidCny: '10',
      consumableCredit: '1000',
      debitCredit: '0.000548',
      creditUnitLabel: '平台额度',
      model: 'gpt-5.6-terra',
      probeVersion: 'cost-calibration-v2',
      costSource: 'response_header',
      probeId: 'probe-demo-a-repeat',
      sampleKind: 'cold',
      resultCny: '0.00000548',
      state: 'completed',
      createdAt: '2026-08-07 20:15',
      updatedAt: '2026-08-07 20:15',
    },
  ],
  responseProbes: [
    {
      id: 'probe-demo-d',
      providerId: 'example-provider-d',
      providerName: '服务商 D',
      model: 'gpt-5.6-terra',
      probeVersion: 'cost-calibration-v2',
      observedAt: '2026-08-07 20:16',
      status: 'final_cost_inline',
      httpStatus: 200,
      requestId: 'preview-demo-d',
      usage: { inputTokens: 12, outputTokens: 4, totalTokens: 16, cachedTokens: 0, cacheWriteTokens: 0, reasoningTokens: 0 },
      costCandidate: '0.000398',
      costSource: 'response_usage',
      detail: '预览样本：已从响应中的用量字段读取费用。',
    },
    {
      id: 'probe-demo-a',
      providerId: 'example-provider-a',
      providerName: '服务商 A',
      model: 'gpt-5.6-terra',
      probeVersion: 'cost-calibration-v2',
      observedAt: '2026-08-07 20:12',
      status: 'correlation_only',
      httpStatus: 200,
      requestId: 'preview-demo-a',
      usage: { inputTokens: 12, outputTokens: 4, totalTokens: 16, cachedTokens: 0, cacheWriteTokens: 0, reasoningTokens: 0 },
      detail: '预览样本：费用由平台日志补充。',
    },
    {
      id: 'probe-demo-a-repeat',
      providerId: 'example-provider-a',
      providerName: '服务商 A',
      model: 'gpt-5.6-terra',
      probeVersion: 'cost-calibration-v2',
      observedAt: '2026-08-07 20:15',
      status: 'final_cost_inline',
      httpStatus: 200,
      requestId: 'preview-demo-a-repeat',
      usage: { inputTokens: 12, outputTokens: 4, totalTokens: 16, cachedTokens: 0, cacheWriteTokens: 0, reasoningTokens: 0 },
      costCandidate: '0.000548',
      costSource: 'response_header',
      detail: '预览样本：已从响应头读取费用。',
    },
  ],
  backups: [
    { id: 'b1', time: '2026-07-01 22:10', label: 'before-20260701-221054', files: 3, fileCategories: ['Codex 设置', '本机登录信息', '恢复说明'], kind: 'before_switch', retentionManaged: true, restoreReady: true, restoreDetail: '可安全恢复：当前服务商设置仍与该次切换后的状态一致。' },
    { id: 'b2', time: '2026-07-01 11:27', label: 'before-20260701-112724', files: 3, fileCategories: ['Codex 设置', '本机登录信息', '恢复说明'], kind: 'before_switch', retentionManaged: true, restoreReady: false, restoreDetail: '这是较早的恢复点。请先恢复最近一次，再继续回退。' },
    { id: 'b3', time: '2026-06-30 10:34', label: 'initial-install', files: 3, fileCategories: ['Codex 设置', '本机登录信息', '恢复说明'], kind: 'initial_install', retentionManaged: false, restoreReady: false, restoreDetail: '首次启动基线备份会一直保留；为避免覆盖后续修改，请按时间从最近恢复点逐步回退。' },
  ],
}
