import type { AppState } from './types'

export const initialState: AppState = {
  currentProfileId: 'a6api',
  configPath: String.raw`C:\Users\ga990\.codex\config.toml`,
  authPath: String.raw`C:\Users\ga990\.codex\auth.json`,
  autoStart: false,
  trayEnabled: true,
  safeMode: true,
  legacySwitcher: {
    profilePath: String.raw`D:\AI Studio\CodeX\Codex Switcher\profiles.json`,
    profileExists: true,
    processRunning: true,
    port: 47831,
    portInUse: true,
    imported: false,
    appProfilePath: String.raw`%LOCALAPPDATA%\CodeX Provider Switcher\profiles.json`,
  },
  profiles: [
    {
      id: 'owl',
      name: 'OWL',
      baseUrl: 'https://api.owlai.tech/v1',
      model: 'gpt-5.5',
      reasoningEffort: 'high',
      note: '默认基线，适合日常使用和原生路由。',
      verified: false,
      isDefault: true,
      active: false,
      hasApiKey: true,
      lastVerifiedAt: '等待完整验证',
    },
    {
      id: 'dasuapi',
      name: 'DasuAPI',
      baseUrl: 'https://dasuapi.com/v1',
      model: 'gpt-5.5',
      reasoningEffort: 'high',
      note: '备用服务商，连通性通过前保持待用。',
      verified: false,
      isDefault: false,
      active: false,
      hasApiKey: true,
      lastVerifiedAt: '连通性降级',
    },
    {
      id: 'a6api',
      name: 'a6api',
      baseUrl: 'https://a6api.com/v1',
      model: 'gpt-5.5',
      reasoningEffort: 'high',
      note: '当前备用配置，本地观察到结构兼容。',
      verified: false,
      isDefault: false,
      active: true,
      hasApiKey: true,
      lastSwitchedAt: '2026-07-01 22:10',
      lastVerifiedAt: '仅完成基础配置检查',
    },
  ],
  checks: [
    {
      id: 'toml',
      label: 'TOML 语法',
      ok: true,
      detail: '配置文件可以正常解析。',
      severity: 'required',
    },
    {
      id: 'root-model',
      label: 'Codex 模型',
      ok: true,
      detail: '根配置中已设置 model。',
      severity: 'required',
    },
    {
      id: 'model-provider',
      label: 'model_provider 已锁定',
      ok: true,
      detail: '已保留预期的 custom 服务商分组。',
      severity: 'required',
    },
    {
      id: 'custom-provider',
      label: 'custom 服务商配置段',
      ok: true,
      detail: '[model_providers.custom] 存在。',
      severity: 'required',
    },
    {
      id: 'wire-api',
      label: 'Responses 线路协议',
      ok: true,
      detail: 'wire_api 保持 responses，兼容 Codex 原生请求。',
      severity: 'required',
    },
    {
      id: 'custom-base-url',
      label: '当前接口地址',
      ok: true,
      detail: 'custom 服务商已配置 base_url。',
      severity: 'required',
    },
    {
      id: 'custom-api-key',
      label: '当前认证密钥',
      ok: true,
      detail: 'custom 服务商已配置 api_key。',
      severity: 'required',
    },
  ],
  activity: [
    {
      id: 'act-1',
      time: '22:26',
      title: '配置安全检查完成',
      detail: 'Codex 当前配置和当前服务商必填项已完成本地检查。',
      tone: 'success',
    },
    {
      id: 'act-2',
      time: '22:13',
      title: '已切换到 a6api',
      detail: '切换前已生成 config.toml 和 auth.json 回滚点。',
      tone: 'success',
    },
    {
      id: 'act-3',
      time: '22:11',
      title: '备份已生成',
      detail: 'before-20260701-221054 可用于高级恢复。',
      tone: 'info',
    },
  ],
  backups: [
    { id: 'b1', time: '2026-07-01 22:10', label: 'before-20260701-221054', files: 2 },
    { id: 'b2', time: '2026-07-01 11:27', label: 'before-20260701-112724', files: 2 },
    { id: 'b3', time: '2026-06-30 10:34', label: 'before-20260630-103413', files: 2 },
  ],
}
