import type { AppState } from './types'

export const initialState: AppState = {
  runtimeMode: 'browser_preview_mock',
  currentProfileId: 'example-provider-a',
  configPath: String.raw`C:\Users\<user>\.codex\config.toml`,
  authPath: String.raw`C:\Users\<user>\.codex\auth.json`,
  configurationProtection: {
    baselineReady: true,
    baselineDetail: '首次启动基线备份已创建，包含本工具可能写入的 Codex 设置和本机登录信息。',
    restoreDetail: '只恢复服务商设置；其他内容保持不变。',
    items: [
      { id: 'mcp-servers', label: 'MCP 服务', count: 3, state: 'protected', detail: '已设置 3 项，切换时会保留。' },
      { id: 'plugins', label: '插件设置', count: 2, state: 'protected', detail: '已设置 2 项，切换时会保留。' },
      { id: 'projects', label: '项目设置', count: 4, state: 'protected', detail: '已设置 4 项，切换时会保留。' },
      { id: 'hooks', label: '自动化规则', count: 5, state: 'protected', detail: '已设置 5 项，切换时会保留。' },
      { id: 'features', label: '功能偏好', count: 3, state: 'protected', detail: '已设置 3 项，切换时会保留。' },
      { id: 'history', label: '聊天与历史记录', state: 'outside_write_scope', detail: '不属于本工具读写范围，不会读取或改写。' },
    ],
  },
  profiles: [
    {
      id: 'example-provider-c',
      name: '示例服务商 C',
      baseUrl: 'https://provider-c.example/v1',
      model: 'reasoning-preview',
      reasoningEffort: 'high',
      note: '演示用额度失败状态。开发预览不会连接真实服务商。',
      verified: false,
      verificationStatus: 'billing_unavailable',
      isDefault: true,
      active: false,
      hasApiKey: true,
      lastVerifiedAt: '2026-07-29 10:42',
      lastVerificationDetail: '服务商返回额度不足，未写入 Codex 配置。',
      lastVerificationStage: 'billing',
      lastVerificationHttpStatus: 429,
      lastVerificationProviderCode: 'insufficient_quota',
    },
    {
      id: 'example-provider-b',
      name: '示例服务商 B',
      baseUrl: 'https://provider-b.example/v1',
      model: '',
      reasoningEffort: 'high',
      note: '演示用响应形状待确认状态。',
      verified: false,
      verificationStatus: 'response_shape_unconfirmed',
      isDefault: false,
      active: false,
      hasApiKey: true,
      lastVerifiedAt: '2026-07-29 10:38',
      lastVerificationDetail: '服务端已返回 JSON，但无法确认其可供 Codex 使用。',
      lastVerificationStage: 'response_shape',
      lastVerificationHttpStatus: 200,
    },
    {
      id: 'example-provider-d',
      name: '示例服务商 D',
      baseUrl: 'https://provider-d.example/v1',
      model: 'reasoning-verified',
      reasoningEffort: 'high',
      note: '演示用已验证状态。',
      verified: true,
      verificationStatus: 'verified',
      isDefault: false,
      active: false,
      hasApiKey: true,
      lastVerifiedAt: '2026-07-29 10:34',
      lastVerificationDetail: '短时 Responses 请求返回可识别的模型输出。',
      lastVerificationStage: 'inference',
      lastVerificationHttpStatus: 200,
      verificationResponseShape: 'standard_responses',
    },
    {
      id: 'example-provider-a',
      name: '示例服务商 A',
      baseUrl: 'https://provider-a.example/v1',
      model: '',
      reasoningEffort: 'high',
      note: '演示用当前配置。真实服务商信息只保存在本机。',
      verified: true,
      verificationStatus: 'verified',
      isDefault: false,
      active: true,
      hasApiKey: true,
      lastSwitchedAt: '2026-07-01 22:10',
      lastVerifiedAt: '2026-07-29 10:36',
      lastVerificationDetail: '短时 Responses 请求返回可识别的模型输出。',
      lastVerificationStage: 'inference',
      lastVerificationHttpStatus: 200,
      verificationResponseShape: 'standard_responses',
    },
  ],
  modelCatalogs: [
    {
      providerId: 'example-provider-a',
      baseUrl: 'https://provider-a.example/v1',
      fetchedAt: '2026-07-14 18:00:00',
      status: 'not_fetched',
      statusDetail: '尚未刷新模型目录。刷新后只展示中转站实际返回的模型列表。',
      models: [],
    },
  ],
  checks: [
    {
      id: 'toml',
      label: 'TOML 语法',
      ok: true,
      detail: '配置文件可以正常解析。',
      severity: 'required',
    },
    {
      id: 'root-model',
      label: 'Codex 模型',
      ok: true,
      detail: '根配置中已设置 model。',
      severity: 'required',
    },
    {
      id: 'model-provider',
      label: 'model_provider 已锁定',
      ok: true,
      detail: '已保留预期的 custom 服务商分组。',
      severity: 'required',
    },
    {
      id: 'custom-provider',
      label: 'custom 服务商配置段',
      ok: true,
      detail: '[model_providers.custom] 存在。',
      severity: 'required',
    },
    {
      id: 'wire-api',
      label: 'Responses 线路协议',
      ok: true,
      detail: 'wire_api 保持 responses，兼容 Codex 原生请求。',
      severity: 'required',
    },
    {
      id: 'custom-base-url',
      label: '当前接口地址',
      ok: true,
      detail: 'custom 服务商已配置 base_url。',
      severity: 'required',
    },
    {
      id: 'custom-api-key',
      label: '当前认证密钥',
      ok: true,
      detail: 'custom 服务商已配置 api_key。',
      severity: 'required',
    },
  ],
  activity: [
    {
      id: 'act-1',
      time: '22:26',
      title: '配置安全检查完成',
      detail: 'Codex 当前配置和当前服务商必填项已完成本地检查。',
      tone: 'success',
    },
    {
      id: 'act-2',
      time: '22:13',
      title: '已切换到示例服务商 A',
      detail: '切换前已生成 config.toml 和 auth.json 回滚点。',
      tone: 'success',
    },
    {
      id: 'act-3',
      time: '22:11',
      title: '备份已生成',
      detail: 'before-20260701-221054 可用于高级恢复。',
      tone: 'info',
    },
  ],
  backups: [
    { id: 'b1', time: '2026-07-01 22:10', label: 'before-20260701-221054', files: 3, fileCategories: ['Codex 设置', '本机登录信息', '恢复说明'], kind: 'before_switch', restoreReady: true, restoreDetail: '可安全恢复：当前服务商设置仍与该次切换后的状态一致。' },
    { id: 'b2', time: '2026-07-01 11:27', label: 'before-20260701-112724', files: 3, fileCategories: ['Codex 设置', '本机登录信息', '恢复说明'], kind: 'before_switch', restoreReady: false, restoreDetail: '这是较早的恢复点。请先恢复最近一次，再继续回退。' },
    { id: 'b3', time: '2026-06-30 10:34', label: 'initial-install', files: 3, fileCategories: ['Codex 设置', '本机登录信息', '恢复说明'], kind: 'initial_install', restoreReady: false, restoreDetail: '首次启动基线备份会一直保留；为避免覆盖后续修改，请按时间从最近恢复点逐步回退。' },
  ],
}
